version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rds-mysql-idle-shutdown"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-n1pqal5dxcyy"
s3_prefix = "rds-mysql-idle-shutdown"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
