AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-rds-mysql-idle-shutdown

  Periodically queries RDS instances, and if they're idle, shuts them down

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 90

Resources:
  IdleRDSShutdownFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: idle_shutdown/
      Handler: app.lambda_handler
      Policies: arn:aws:iam::036372598227:policy/rds-idle-shutdown
      Runtime: python3.8
      VpcConfig:
        SecurityGroupIds:
          - sg-8b5c50ee
        SubnetIds:
          - subnet-6577a03c
          - subnet-a752c0c2
          - subnet-325eee45
      Events:
        IdleRDSShutdown:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt IdleRDSShutdownFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt IdleRDSShutdownFunctionRole.Arn
